import { IconBrain, IconCrown, IconRocket, IconSchool, IconSword } from "@tabler/icons-react";
import type { PracticeCategory } from "../PracticePage";

export const practiceCategories: PracticeCategory[] = [
  {
    group: "Checkmates",
    id: "piece-checkmates-1",
    title: "Piece Checkmates I",
    description: "Basic checkmates",
    icon: <IconCrown size={24} />,
    color: "yellow",
    estimatedTime: 0,
    exercises: [
      {
        id: "mate-queen-rook",
        title: "Queen and rook mate",
        description:
          "Use your queen and rook to restrict the king and deliver checkmate. Mate in 3 if played perfectly.",
        difficulty: "beginner",
        fen: "8/8/2k5/8/8/4K3/8/Q6R w - - 0 1",
        correctMoves: [],
        points: 10,
        timeLimit: 30,
      },
    ],
  },
  {
    group: "Checkmates",
    id: "checkmate-patterns-1",
    title: "Checkmate Patterns I",
    description: "Recognize the patterns",
    icon: <IconCrown size={24} />,
    color: "yellow",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Checkmates",
    id: "checkmate-patterns-2",
    title: "Checkmate Patterns II",
    description: "Recognize the patterns",
    icon: <IconCrown size={24} />,
    color: "yellow",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Checkmates",
    id: "checkmate-patterns-3",
    title: "Checkmate Patterns III",
    description: "Recognize the patterns",
    icon: <IconCrown size={24} />,
    color: "yellow",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Checkmates",
    id: "checkmate-patterns-4",
    title: "Checkmate Patterns IV",
    description: "Recognize the patterns",
    icon: <IconCrown size={24} />,
    color: "yellow",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Checkmates",
    id: "piece-checkmates-2",
    title: "Piece Checkmates II",
    description: "Challenging checkmates",
    icon: <IconCrown size={24} />,
    color: "yellow",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Checkmates",
    id: "knight-bishop-mate",
    title: "Knight & Bishop Mate",
    description: "Interactive lesson",
    icon: <IconCrown size={24} />,
    color: "yellow",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Basic Tactics",
    id: "the-pin",
    title: "The Pin",
    description: "Pin it to win it",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Basic Tactics",
    id: "the-skewer",
    title: "The Skewer",
    description: "Yum - skewers!",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Basic Tactics",
    id: "the-fork",
    title: "The Fork",
    description: "Use the fork, Luke",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Basic Tactics",
    id: "discovered-attacks",
    title: "Discovered Attacks",
    description: "Including discovered checks",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Basic Tactics",
    id: "double-check",
    title: "Double Check",
    description: "A very powerful tactic",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Basic Tactics",
    id: "overloaded-pieces",
    title: "Overloaded Pieces",
    description: "They have too much work",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Basic Tactics",
    id: "zwischenzug",
    title: "Zwischenzug",
    description: "In-between moves",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Basic Tactics",
    id: "x-ray",
    title: "X-Ray",
    description: "Attacking through an enemy piece",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Intermediate Tactics",
    id: "zugzwang",
    title: "Zugzwang",
    description: "Being forced to move",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Intermediate Tactics",
    id: "interference",
    title: "Interference",
    description: "Interpose a piece to great effect",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Intermediate Tactics",
    id: "greek-gift",
    title: "Greek Gift",
    description: "Study the Greek Gift sacrifice",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Intermediate Tactics",
    id: "deflection",
    title: "Deflection",
    description: "Distracting a defender",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Intermediate Tactics",
    id: "attraction",
    title: "Attraction",
    description: "Lure a piece to a bad square",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Intermediate Tactics",
    id: "underpromotion",
    title: "Underpromotion",
    description: "Promote - but not to a queen!",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Intermediate Tactics",
    id: "desperado",
    title: "Desperado",
    description: "A piece is lost, but it can still help",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Intermediate Tactics",
    id: "counter-check",
    title: "Counter Check",
    description: "Respond to a check with a check",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Intermediate Tactics",
    id: "undermining",
    title: "Undermining",
    description: "Remove the defending piece",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Intermediate Tactics",
    id: "clearance",
    title: "Clearance",
    description: "Get out of the way!",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Pawn Endgames",
    id: "key-squares",
    title: "Key Squares",
    description: "Reach a key square",
    icon: <IconSchool size={24} />,
    color: "green",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Pawn Endgames",
    id: "opposition",
    title: "Opposition",
    description: "Take the opposition",
    icon: <IconSchool size={24} />,
    color: "green",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Pawn Endgames",
    id: "rook-pawn-7th-queen",
    title: "7th-Rank Rook Pawn",
    description: "Versus a Queen",
    icon: <IconSchool size={24} />,
    color: "green",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Rook Endgames",
    id: "rook-pawn-7th-rook",
    title: "7th-Rank Rook Pawn",
    description: "And Passive Rook vs Rook",
    icon: <IconRocket size={24} />,
    color: "purple",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Rook Endgames",
    id: "basic-rook-endgames",
    title: "Basic Rook Endgames",
    description: "Lucena and Philidor",
    icon: <IconRocket size={24} />,
    color: "purple",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Rook Endgames",
    id: "intermediate-rook-endings",
    title: "Intermediate Rook Endings",
    description: "Broaden your knowledge",
    icon: <IconRocket size={24} />,
    color: "purple",
    estimatedTime: 0,
    exercises: [],
  },
  {
    group: "Rook Endgames",
    id: "practical-rook-endings",
    title: "Practical Rook Endings",
    description: "Rook endings with several pawns",
    icon: <IconRocket size={24} />,
    color: "purple",
    estimatedTime: 0,
    exercises: [],
  },
];
