import { IconBrain, IconCrown, IconRocket, IconSchool, IconSword } from "@tabler/icons-react";
import type { PracticeCategory } from "../PracticePage";

export const practiceCategories: PracticeCategory[] = [
  // ♟️ Checkmates
  {
    group: "Checkmates",
    id: "piece-checkmates-1",
    title: "Piece Checkmates I",
    description: "Basic checkmates",
    icon: <IconCrown size={24} />,
    color: "yellow",
    estimatedTime: 10,
    exercises: [
      {
        id: "mate-in-1-1",
        title: "Mate in 1: Rook & King",
        description: "White to move and checkmate in one move.",
        difficulty: "beginner",
        fen: "8/8/8/8/8/5k2/6R1/6K1 w - - 0 1",
        correctMoves: ["Rg4#"],
        points: 10,
        timeLimit: 30,
      },
      {
        id: "mate-in-1-2",
        title: "Mate in 1: Queen & King",
        description: "White to move and checkmate in one move.",
        difficulty: "beginner",
        fen: "6k1/8/8/8/8/8/6Q1/6K1 w - - 0 1",
        correctMoves: ["Qg7#"],
        points: 10,
        timeLimit: 30,
      },
      {
        id: "mate-in-1-3",
        title: "Mate in 1: Two Rooks",
        description: "White to move and checkmate in one move.",
        difficulty: "beginner",
        fen: "8/8/8/8/8/5k2/6R1/6KR w - - 0 1",
        correctMoves: ["Rg3#"],
        points: 10,
        timeLimit: 30,
      },
    ],
  },
  {
    group: "Checkmates",
    id: "checkmate-patterns-1",
    title: "Checkmate Patterns I",
    description: "Recognize the patterns",
    icon: <IconCrown size={24} />,
    color: "yellow",
    estimatedTime: 10,
    exercises: [
      {
        id: "back-rank-mate-1",
        title: "Back Rank Mate",
        description: "White to move and deliver back rank mate.",
        difficulty: "beginner",
        fen: "6k1/5ppp/8/8/8/8/5PPP/6KR w - - 0 1",
        correctMoves: ["Re1#"],
        points: 10,
        timeLimit: 30,
      },
      {
        id: "back-rank-mate-2",
        title: "Back Rank Mate II",
        description: "White to move and deliver mate on the back rank.",
        difficulty: "beginner",
        fen: "6k1/5ppp/8/8/8/8/5PPP/5QKR w - - 0 1",
        correctMoves: ["Qe8#"],
        points: 12,
        timeLimit: 30,
      },
      {
        id: "back-rank-mate-3",
        title: "Back Rank Mate III",
        description: "White to move and deliver mate on the back rank.",
        difficulty: "intermediate",
        fen: "6k1/5ppp/8/8/8/8/5PPP/4Q1KR w - - 0 1",
        correctMoves: ["Qe8#"],
        points: 14,
        timeLimit: 40,
      },
    ],
  },
  {
    group: "Checkmates",
    id: "checkmate-patterns-2",
    title: "Checkmate Patterns II",
    description: "Recognize the patterns",
    icon: <IconCrown size={24} />,
    color: "yellow",
    estimatedTime: 10,
    exercises: [
      {
        id: "smothered-mate-1",
        title: "Smothered Mate",
        description: "White to move and checkmate in one move.",
        difficulty: "intermediate",
        fen: "6rk/5Qpp/8/8/8/8/6PP/6K1 w - - 0 1",
        correctMoves: ["Qxg7#"],
        points: 12,
        timeLimit: 40,
      },
      {
        id: "smothered-mate-2",
        title: "Smothered Mate II",
        description: "White to move and checkmate in one move.",
        difficulty: "intermediate",
        fen: "6k1/5ppp/8/8/8/8/6PP/5NKR w - - 0 1",
        correctMoves: ["Nh6#"],
        points: 14,
        timeLimit: 40,
      },
    ],
  },
  {
    group: "Checkmates",
    id: "checkmate-patterns-3",
    title: "Checkmate Patterns III",
    description: "Recognize the patterns",
    icon: <IconCrown size={24} />,
    color: "yellow",
    estimatedTime: 10,
    exercises: [
      {
        id: "arabian-mate-1",
        title: "Arabian Mate",
        description: "White to move and checkmate in one move.",
        difficulty: "intermediate",
        fen: "6k1/8/8/8/8/6N1/6PP/6KR w - - 0 1",
        correctMoves: ["Nh6#"],
        points: 12,
        timeLimit: 40,
      },
      {
        id: "arabian-mate-2",
        title: "Arabian Mate II",
        description: "White to move and checkmate in one move.",
        difficulty: "intermediate",
        fen: "6k1/8/8/8/8/6N1/6PP/5NKR w - - 0 1",
        correctMoves: ["Nf6#"],
        points: 14,
        timeLimit: 40,
      },
    ],
  },
  {
    group: "Checkmates",
    id: "checkmate-patterns-4",
    title: "Checkmate Patterns IV",
    description: "Recognize the patterns",
    icon: <IconCrown size={24} />,
    color: "yellow",
    estimatedTime: 10,
    exercises: [
      {
        id: "smothered-mate-2",
        title: "Smothered Mate II",
        description: "White to move and checkmate in one move.",
        difficulty: "advanced",
        fen: "6k1/8/8/8/8/6N1/6PP/6KR w - - 0 1",
        correctMoves: ["Nh6#"],
        points: 15,
        timeLimit: 45,
      },
      {
        id: "smothered-mate-3",
        title: "Smothered Mate III",
        description: "White to move and checkmate in one move.",
        difficulty: "advanced",
        fen: "6k1/8/8/8/8/6N1/6PP/5NKR w - - 0 1",
        correctMoves: ["Nf6#"],
        points: 16,
        timeLimit: 45,
      },
    ],
  },
  {
    group: "Checkmates",
    id: "piece-checkmates-2",
    title: "Piece Checkmates II",
    description: "Challenging checkmates",
    icon: <IconCrown size={24} />,
    color: "yellow",
    estimatedTime: 12,
    exercises: [
      {
        id: "mate-in-2-1",
        title: "Mate in 2: Queen & King",
        description: "White to move and checkmate in two moves.",
        difficulty: "intermediate",
        fen: "6k1/8/8/8/8/8/6Q1/6K1 w - - 0 1",
        correctMoves: ["Qa8+", "Qxa8#"],
        points: 15,
        timeLimit: 45,
      },
      {
        id: "mate-in-2-2",
        title: "Mate in 2: Rook & King",
        description: "White to move and checkmate in two moves.",
        difficulty: "intermediate",
        fen: "8/8/8/8/8/5k2/6R1/6K1 w - - 0 1",
        correctMoves: ["Rg4+", "Rg1#"],
        points: 15,
        timeLimit: 45,
      },
    ],
  },
  {
    group: "Checkmates",
    id: "knight-bishop-mate",
    title: "Knight & Bishop Mate",
    description: "Interactive lesson",
    icon: <IconCrown size={24} />,
    color: "yellow",
    estimatedTime: 15,
    exercises: [
      {
        id: "knight-bishop-mate-1",
        title: "Knight & Bishop Mate",
        description: "White to move and checkmate in two moves.",
        difficulty: "advanced",
        fen: "8/8/8/8/8/2B5/3N4/2K1k3 w - - 0 1",
        correctMoves: ["Nd4#"],
        points: 20,
        timeLimit: 60,
      },
      {
        id: "knight-bishop-mate-2",
        title: "Knight & Bishop Mate II",
        description: "White to move and checkmate in two moves.",
        difficulty: "advanced",
        fen: "8/8/8/8/8/2B5/3N4/2K1k2N w - - 0 1",
        correctMoves: ["Nd4#"],
        points: 22,
        timeLimit: 60,
      },
    ],
  },
  // 🧠 Basic Tactics
  {
    group: "Basic Tactics",
    id: "the-pin",
    title: "The Pin",
    description: "Pin it to win it",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 10,
    exercises: [
      {
        id: "pin-1",
        title: "Pin the Knight",
        description: "White to move and pin the black knight.",
        difficulty: "beginner",
        fen: "rnbqkbnr/pppp1ppp/8/4p3/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 0 3",
        correctMoves: ["Bg5"],
        points: 10,
        timeLimit: 30,
      },
      {
        id: "pin-2",
        title: "Pin the Bishop",
        description: "White to move and pin the bishop to the king.",
        difficulty: "beginner",
        fen: "rnbqkbnr/pppp1ppp/8/4p3/3P4/8/PPP1PPPP/RNBQK1NR w KQkq - 0 3",
        correctMoves: ["Bg5"],
        points: 10,
        timeLimit: 30,
      },
    ],
  },
  {
    group: "Basic Tactics",
    id: "the-skewer",
    title: "The Skewer",
    description: "Yum - skewers!",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 10,
    exercises: [
      {
        id: "skewer-1",
        title: "Skewer the Queen",
        description: "White to move and skewer the queen.",
        difficulty: "beginner",
        fen: "4r1k1/1pp2ppp/p1n5/8/8/2N5/PPP2PPP/2KR3R w - - 0 1",
        correctMoves: ["Rhe1"],
        points: 10,
        timeLimit: 30,
      },
      {
        id: "skewer-2",
        title: "Skewer the Rook",
        description: "White to move and skewer the rook.",
        difficulty: "beginner",
        fen: "4r1k1/1pp2ppp/p1n5/8/8/2N5/PPP2PPP/2KR2R1 w - - 0 1",
        correctMoves: ["Rhe1"],
        points: 10,
        timeLimit: 30,
      },
    ],
  },
  {
    group: "Basic Tactics",
    id: "the-fork",
    title: "The Fork",
    description: "Use the fork, Luke",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 10,
    exercises: [
      {
        id: "fork-1",
        title: "Knight Fork",
        description: "White to move and fork the king and rook.",
        difficulty: "beginner",
        fen: "8/8/8/8/8/2N5/5k2/6K1 w - - 0 1",
        correctMoves: ["Nd1+"],
        points: 10,
        timeLimit: 30,
      },
      {
        id: "fork-2",
        title: "Pawn Fork",
        description: "White to move and fork two pieces with a pawn.",
        difficulty: "beginner",
        fen: "8/8/8/8/8/2N5/5k2/6KP w - - 0 1",
        correctMoves: ["h4"],
        points: 10,
        timeLimit: 30,
      },
    ],
  },
  {
    group: "Basic Tactics",
    id: "discovered-attacks",
    title: "Discovered Attacks",
    description: "Including discovered checks",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 10,
    exercises: [
      {
        id: "discovered-attack-1",
        title: "Discovered Attack",
        description: "White to move and create a discovered attack.",
        difficulty: "intermediate",
        fen: "r1bqkbnr/pppp1ppp/2n5/4p3/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 0 4",
        correctMoves: ["d5"],
        points: 12,
        timeLimit: 40,
      },
      {
        id: "discovered-attack-2",
        title: "Discovered Check",
        description: "White to move and deliver a discovered check.",
        difficulty: "intermediate",
        fen: "r1bqkbnr/pppp1ppp/2n5/4p3/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 0 4",
        correctMoves: ["dxe5+"],
        points: 14,
        timeLimit: 40,
      },
    ],
  },
  {
    group: "Basic Tactics",
    id: "double-check",
    title: "Double Check",
    description: "A very powerful tactic",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 10,
    exercises: [
      {
        id: "double-check-1",
        title: "Double Check",
        description: "White to move and deliver double check.",
        difficulty: "intermediate",
        fen: "rnbqkbnr/pppp1ppp/8/4p3/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 0 3",
        correctMoves: ["Bb5+"],
        points: 12,
        timeLimit: 40,
      },
      {
        id: "double-check-2",
        title: "Double Check II",
        description: "White to move and deliver double check with a knight.",
        difficulty: "intermediate",
        fen: "rnbqkbnr/pppp1ppp/8/4p3/3P4/8/PPP1PPPP/RNBQK1NR w KQkq - 0 3",
        correctMoves: ["Nd5+"],
        points: 14,
        timeLimit: 40,
      },
    ],
  },
  {
    group: "Basic Tactics",
    id: "overloaded-pieces",
    title: "Overloaded Pieces",
    description: "They have too much work",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 10,
    exercises: [
      {
        id: "overloaded-1",
        title: "Overloaded Piece",
        description: "White to move and exploit the overloaded defender.",
        difficulty: "intermediate",
        fen: "r1bqkbnr/pppp1ppp/2n5/4p3/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 0 4",
        correctMoves: ["dxe5"],
        points: 12,
        timeLimit: 40,
      },
    ],
  },
  {
    group: "Basic Tactics",
    id: "zwischenzug",
    title: "Zwischenzug",
    description: "In-between moves",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 10,
    exercises: [
      {
        id: "zwischenzug-1",
        title: "Zwischenzug",
        description: "White to move and play an in-between move.",
        difficulty: "intermediate",
        fen: "rnbqkbnr/pppp1ppp/8/4p3/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 0 3",
        correctMoves: ["dxe5"],
        points: 12,
        timeLimit: 40,
      },
    ],
  },
  {
    group: "Basic Tactics",
    id: "x-ray",
    title: "X-Ray",
    description: "Attacking through an enemy piece",
    icon: <IconSword size={24} />,
    color: "red",
    estimatedTime: 10,
    exercises: [
      {
        id: "xray-1",
        title: "X-Ray Attack",
        description: "White to move and create an x-ray attack.",
        difficulty: "intermediate",
        fen: "r1bqkbnr/pppp1ppp/2n5/4p3/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 0 4",
        correctMoves: ["Bb5"],
        points: 12,
        timeLimit: 40,
      },
    ],
  },
  // 🧠 Intermediate Tactics
  {
    group: "Intermediate Tactics",
    id: "zugzwang",
    title: "Zugzwang",
    description: "Being forced to move",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 12,
    exercises: [
      {
        id: "zugzwang-1",
        title: "Zugzwang",
        description: "White to move and put black in zugzwang.",
        difficulty: "intermediate",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["Kf2"],
        points: 15,
        timeLimit: 45,
      },
    ],
  },
  {
    group: "Intermediate Tactics",
    id: "interference",
    title: "Interference",
    description: "Interpose a piece to great effect",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 12,
    exercises: [
      {
        id: "interference-1",
        title: "Interference",
        description: "White to move and interpose a piece.",
        difficulty: "intermediate",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["Ne2"],
        points: 15,
        timeLimit: 45,
      },
    ],
  },
  {
    group: "Intermediate Tactics",
    id: "greek-gift",
    title: "Greek Gift",
    description: "Study the Greek Gift sacrifice",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 12,
    exercises: [
      {
        id: "greek-gift-1",
        title: "Greek Gift Sacrifice",
        description: "White to move and play the Greek Gift.",
        difficulty: "advanced",
        fen: "rnbqkbnr/pppp1ppp/8/4p3/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 0 3",
        correctMoves: ["Bxh7+"],
        points: 18,
        timeLimit: 50,
      },
    ],
  },
  {
    group: "Intermediate Tactics",
    id: "deflection",
    title: "Deflection",
    description: "Distracting a defender",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 12,
    exercises: [
      {
        id: "deflection-1",
        title: "Deflection",
        description: "White to move and deflect the defender.",
        difficulty: "intermediate",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["Kf2"],
        points: 15,
        timeLimit: 45,
      },
    ],
  },
  {
    group: "Intermediate Tactics",
    id: "attraction",
    title: "Attraction",
    description: "Lure a piece to a bad square",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 12,
    exercises: [
      {
        id: "attraction-1",
        title: "Attraction",
        description: "White to move and lure a piece.",
        difficulty: "intermediate",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["Kf2"],
        points: 15,
        timeLimit: 45,
      },
    ],
  },
  {
    group: "Intermediate Tactics",
    id: "underpromotion",
    title: "Underpromotion",
    description: "Promote - but not to a queen!",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 12,
    exercises: [
      {
        id: "underpromotion-1",
        title: "Underpromotion",
        description: "White to move and promote to a knight.",
        difficulty: "advanced",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["g8=N"],
        points: 18,
        timeLimit: 50,
      },
    ],
  },
  {
    group: "Intermediate Tactics",
    id: "desperado",
    title: "Desperado",
    description: "A piece is lost, but it can still help",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 12,
    exercises: [
      {
        id: "desperado-1",
        title: "Desperado",
        description: "White to move and use the desperado tactic.",
        difficulty: "advanced",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["Bxf7+"],
        points: 18,
        timeLimit: 50,
      },
    ],
  },
  {
    group: "Intermediate Tactics",
    id: "counter-check",
    title: "Counter Check",
    description: "Respond to a check with a check",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 12,
    exercises: [
      {
        id: "counter-check-1",
        title: "Counter Check",
        description: "White to move and respond to a check with a check.",
        difficulty: "advanced",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["Re2+"],
        points: 18,
        timeLimit: 50,
      },
    ],
  },
  {
    group: "Intermediate Tactics",
    id: "undermining",
    title: "Undermining",
    description: "Remove the defending piece",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 12,
    exercises: [
      {
        id: "undermining-1",
        title: "Undermining",
        description: "White to move and remove the defender.",
        difficulty: "intermediate",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["Bxf7+"],
        points: 15,
        timeLimit: 45,
      },
    ],
  },
  {
    group: "Intermediate Tactics",
    id: "clearance",
    title: "Clearance",
    description: "Get out of the way!",
    icon: <IconBrain size={24} />,
    color: "blue",
    estimatedTime: 12,
    exercises: [
      {
        id: "clearance-1",
        title: "Clearance",
        description: "White to move and clear the way.",
        difficulty: "intermediate",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["Rf1+"],
        points: 15,
        timeLimit: 45,
      },
    ],
  },
  // ♟️ Pawn Endgames
  {
    group: "Pawn Endgames",
    id: "key-squares",
    title: "Key Squares",
    description: "Reach a key square",
    icon: <IconSchool size={24} />,
    color: "green",
    estimatedTime: 10,
    exercises: [
      {
        id: "key-squares-1",
        title: "Key Squares",
        description: "White to move and reach a key square.",
        difficulty: "beginner",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["Kf2"],
        points: 10,
        timeLimit: 30,
      },
    ],
  },
  {
    group: "Pawn Endgames",
    id: "opposition",
    title: "Opposition",
    description: "Take the opposition",
    icon: <IconSchool size={24} />,
    color: "green",
    estimatedTime: 10,
    exercises: [
      {
        id: "opposition-1",
        title: "Opposition",
        description: "White to move and take the opposition.",
        difficulty: "beginner",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["Kf2"],
        points: 10,
        timeLimit: 30,
      },
    ],
  },
  {
    group: "Pawn Endgames",
    id: "rook-pawn-7th-queen",
    title: "7th-Rank Rook Pawn",
    description: "Versus a Queen",
    icon: <IconSchool size={24} />,
    color: "green",
    estimatedTime: 10,
    exercises: [
      {
        id: "rook-pawn-7th-queen-1",
        title: "7th-Rank Rook Pawn vs Queen",
        description: "White to move and draw against the queen.",
        difficulty: "advanced",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["a7"],
        points: 18,
        timeLimit: 50,
      },
    ],
  },
  // 🏰 Rook Endgames
  {
    group: "Rook Endgames",
    id: "rook-pawn-7th-rook",
    title: "7th-Rank Rook Pawn",
    description: "And Passive Rook vs Rook",
    icon: <IconRocket size={24} />,
    color: "purple",
    estimatedTime: 12,
    exercises: [
      {
        id: "rook-pawn-7th-rook-1",
        title: "7th-Rank Rook Pawn vs Rook",
        description: "White to move and hold the draw.",
        difficulty: "advanced",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["a7"],
        points: 18,
        timeLimit: 50,
      },
    ],
  },
  {
    group: "Rook Endgames",
    id: "basic-rook-endgames",
    title: "Basic Rook Endgames",
    description: "Lucena and Philidor",
    icon: <IconRocket size={24} />,
    color: "purple",
    estimatedTime: 12,
    exercises: [
      {
        id: "basic-rook-endgames-1",
        title: "Lucena Position",
        description: "White to move and win with the Lucena position.",
        difficulty: "advanced",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["Rf1+"],
        points: 18,
        timeLimit: 50,
      },
    ],
  },
  {
    group: "Rook Endgames",
    id: "intermediate-rook-endings",
    title: "Intermediate Rook Endings",
    description: "Broaden your knowledge",
    icon: <IconRocket size={24} />,
    color: "purple",
    estimatedTime: 12,
    exercises: [
      {
        id: "intermediate-rook-endings-1",
        title: "Intermediate Rook Endings",
        description: "White to move and win the endgame.",
        difficulty: "advanced",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["Rf1+"],
        points: 18,
        timeLimit: 50,
      },
    ],
  },
  {
    group: "Rook Endgames",
    id: "practical-rook-endings",
    title: "Practical Rook Endings",
    description: "Rook endings with several pawns",
    icon: <IconRocket size={24} />,
    color: "purple",
    estimatedTime: 12,
    exercises: [
      {
        id: "practical-rook-endings-1",
        title: "Practical Rook Endings",
        description: "White to move and win the practical rook ending.",
        difficulty: "advanced",
        fen: "8/8/8/8/8/8/5k2/6K1 w - - 0 1",
        correctMoves: ["Rf1+"],
        points: 18,
        timeLimit: 50,
      },
    ],
  },
];
